package:
  name: dbsink
  version: "2.9.1"

source:
  path: ../

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - click
    - easyavro >=3.0.0
    - geoalchemy2
    - msgpack-python
    - psycopg2
    - python-dateutil
    - pytz
    - shapely
    - simplejson
    - sqlalchemy

test:
  source_files:
    - dbsink
  imports:
    - dbsink
  commands:
    - dbsink --help

about:
  home: https://github.com/axiom-data-science/dbsink
  license: MIT
  summary: 'Read from a kafka topic and sink to a database table, one row per message.'
